apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextjs-chart.fullname" . }}
  labels:
    app: {{ include "nextjs-chart.name" . }}
spec:
  selector:
    app: {{ include "nextjs-chart.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

