replicaCount: 1

image:
  repository: hassanrehman1234/repo1
  pullPolicy: Always
  tag: "latest4"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: "hpc"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

configMap:
  enabled: false
  
containers:
  - name: python-server
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    volumeMounts:
      - name: storage-class-config
        mountPath: /config
        readOnly: true
    lifecycle:
      postStart:
        exec:
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -x;
              apt-get update;
              apt-get install -y curl;


volumes:
  - name: storage-class-config
    configMap:
      name: nfs-storage-class-config

