---
- hosts: k8s
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Execute Script
      ansible.builtin.shell:
        cmd: echo 'Hello World'

  tasks:
    - name: Execute Script
      ansible.builtin.shell:
        cmd: echo 'Hello World'