apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-1234
  namespace: jhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-class  # Use the StorageClass name here
  resources:
    requests:
      storage: 1Gi

