apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: j-db-dir-4
  namespace: jhub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage-class  # Use the StorageClass name here
  resources:
    requests:
      storage: 1Gi

