apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-mariadb
  namespace: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage-class
  resources:
    requests:
      storage: 4Gi