apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-pv1
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /shared/nfs  # Path on the NFS server
    server: 192.168.56.10     # IP address of VM1
    # Use the StorageClass name here
