apiVersion: v1
kind: Service
metadata:
  name: istio-ingress-nodeport
  namespace: istio-system
spec:
  type: NodePort
  selector:
    app: istio-ingressgateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31380  # Choose a suitable nodePort number, or let Kubernetes allocate one

