---
- hosts: all
  become: true
  tasks:
  - name: Install necessary packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common 
      - gnupg2
      - net-tools
      - containerd
      - gnupg

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Ensure the Kubernetes apt keyring directory exists
    become: yes
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download and install the Kubernetes signing key
    ansible.builtin.get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      dest: /tmp/kubernetes-release.key
    register: download_key

  - name: Add the Kubernetes signing key
    ansible.builtin.shell:
      cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
    when: download_key.changed

  - name: Add the Kubernetes apt repository
    ansible.builtin.apt_repository:
      repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
      filename: kubernetes.list
      state: present

  - name: Update the apt package index again
    ansible.builtin.apt:
      update_cache: yes

  - name: Install kubelet, kubeadm, and kubectl
    ansible.builtin.apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present

  - name: Mark kubelet, kubeadm, and kubectl to hold
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: no
      dpkg_options: 'force-confold,force-confdef'
    loop:
      - kubelet
      - kubeadm
      - kubectl
    notify: Hold kubelet, kubeadm, and kubectl

  - name: Configure containerd
    blockinfile:
      create: true
      path: /etc/modules-load.d/containerd.conf
      block: |
        overlay
        br_netfilter

  - name: Enable kernel modules
    shell: |
      modprobe overlay
      modprobe br_netfilter

  - name: Configure IP forwarding and iptables
    blockinfile:
      create: true
      path: /etc/sysctl.conf
      block: |
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1

  - name: Persist changes
    command: sysctl -p

  - name: Get IP eth1 addr
    shell: ifconfig eth1 | grep 'inet' | cut -d{{':'}} -f2 | awk '{ print $2 }'
    register: output

  - name: Configure kubelet
    lineinfile:
      path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
      line: Environment="KUBELET_EXTRA_ARGS=--node-ip={{ output.stdout }}"

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="192.168.56.10" --apiserver-cert-extra-sans="192.168.56.10" --pod-network-cidr=172.16.0.0/16 

  - name: Create kube directory
    file:
      path: /home/vagrant/.kube
      state: directory

  - name: Setup kubeconfig for vagrant user
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: yes
      owner: vagrant
      group: vagrant
      mode: '0644'
      
  - ansible.builtin.apt:
      update_cache: true
    name: Update apt package cache

  - ansible.builtin.apt:
      name: docker.io
      state: present
    name: Install Docker

  - ansible.builtin.service:
      name: docker
      state: started
    name: Ensure Docker service is started

  - name: Download calico.conf
    get_url:
      url: https://docs.projectcalico.org/manifests/calico.yaml
      dest: /home/vagrant/calico.yaml

  - name: Add pod config to calico.yaml
    lineinfile:
      dest: /home/vagrant/calico.yaml
      regexp: '^\s{12}#\s*- name: CALICO_IPV4POOL_CIDR.*$'
      line: '            - name: CALICO_IPV4POOL_CIDR'

  - name: Add pod config to calico.yaml
    lineinfile:
      dest: /home/vagrant/calico.yaml
      regexp: '^\s{12}#\s*  value: "192.168.0.0\/16".*$'
      line: '              value: "172.16.0.0/16"'
      
  - name: Install calico CNI
    become: false
    command: kubectl create -f calico.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"


  - name: Install NFS kernel server
    apt:
      name: nfs-kernel-server
      state: present
      update_cache: yes

  - name: Create NFS shared directory
    file:
      path: /shared/nfs
      state: directory
      mode: '0777'
        
  - name: Add NFS export entry to /etc/exports
    lineinfile:
      path: /etc/exports
      line: "/shared/nfs *(rw,sync,no_subtree_check)"
      insertafter: EOF

  - name: Restart NFS server
    service:
      name: nfs-server
      state: restarted
