apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: developer-user
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io

