apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-authservice-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/my-authservice-data  # Specify the path on the host machine
